export const Cards = [
    {
        category: 'Meat',
        image: './public/assets/images/italian.png',
        name: 'Italian',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '8.35',
        button: 'Order Now',
    },
    {   
        category: 'Meat',
        image: './public/assets/images/venecia.png',
        name: 'Venecia',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '7.35',
        button: 'Order Now',
    },
    {
        category: 'Meat',
        image: './public/assets/images/meat.png',
        name: 'Meat',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '9.35',
        button: 'Order Now',
    },
    {
        category: 'Vegetarian',
        image: './public/assets/images/cheese.png',
        name: 'Cheese',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '8.35',
        button: 'Order Now',
    },
    {
        category: 'Sea Products',
        image: './public/assets/images/argentina.png',
        name: 'Argentina',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '7.35',
        button: 'Order Now',
    },
    {
        category: 'Mushroom',
        image: './public/assets/images/grybnaja.png',
        name: 'Gribnaya',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '6.35',
        button: 'Order Now',
    },
    {
        category: 'Vegetarian',
        image: './public/assets/images/tomato.png',
        name: 'Tomato',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '7.35',
        button: 'Order Now',
    },
    {
        category: 'Meat',
        image: './public/assets/images/italianx2.png',
        name: 'Italian x2',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '8.35',
        button: 'Order Now',
    },
]