export const Cards = [
    {
        image: './public/assets/images/italian.png',
        name: 'Italian',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '8,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/venecia.png',
        name: 'Venecia',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '7,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/meat.png',
        name: 'Meat',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '9,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/cheese.png',
        name: 'Cheese',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '8,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/cheese.png',
        name: 'Argentina',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '7,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/cheese.png',
        name: 'Gribnays',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '6,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/cheese.png',
        name: 'Tomato',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '7,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/cheese.png',
        name: 'Italian x2',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '8,35',
        button: 'Order Now',
    },
]