export const Cards = [
    {
        image: './public/assets/images/italian.png',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '8,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/venecia.png',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '7,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/meat.png',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '9,35',
        button: 'Order Now',
    },
    {
        image: './public/assets/images/cheese.png',
        ingrediants: 'Filling: onion, potato, tomato, mushrooms, cheese, olives, meat',
        size1: '22',
        size2: '28',
        size3: '33',
        addIngredients: '+ Ingredients',
        price: '8,35',
        button: 'Order Now',
    }
]